# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - cippcs7q2

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F4883CBDB14B4945AA0E69FFEE6F7562 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B8BDC40DC501436ABDF712E51361419E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9F5B7BFF63E242338ED19C870334261C }}

      - name: Create deployment package
        shell: pwsh
        run: |
          $staging = "staging"

          if (Test-Path $staging) {
            Remove-Item $staging -Recurse -Force
          }

          New-Item -ItemType Directory -Path $staging | Out-Null

          robocopy "." "$staging" /E /XD ".git" ".github" ".vscode" /XF "*.md"
          $rc = $LASTEXITCODE

          # Robocopy returns 0-7 for success, 8+ for failure
          if ($rc -ge 8) {
            throw "Robocopy failed with exit code $rc"
          }

          cmd /c exit 0

          if (Test-Path "package.zip") {
            Remove-Item "package.zip" -Force
          }

          Compress-Archive -Path "$staging\*" -DestinationPath "package.zip" -Force



      - name: Deploy via Azure CLI zip deploy
        shell: bash
        run: |
          az functionapp deployment source config-zip \
            --resource-group rg-cipp-prod \
            --name cippcs7q2 \
            --src package.zip




